#!/bin/bash
# Generated by `cs build` - do not edit.
# @raycast.schemaVersion 1
# @raycast.title Git Essential Commands Cheatsheet
# @raycast.mode silent
# @raycast.packageName Cheatsheets
# @raycast.icon 📒
# @raycast.description Open the Git Essential Commands cheatsheet. Tags: git, vcs, version-control, source-control, cli, terminal
export PATH="/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:$PATH"
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
"$DIR/cs" open --id git
