#!/bin/bash
# Generated by `cs build` - do not edit.
# @raycast.schemaVersion 1
# @raycast.title IntelliJ IDEA macOS Shortcuts Cheatsheet
# @raycast.mode silent
# @raycast.packageName Cheatsheets
# @raycast.icon 📒
# @raycast.description Open the IntelliJ IDEA macOS Shortcuts cheatsheet. Tags: intellij, idea, jetbrains, ide, shortcuts, keyboard
export PATH="/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:$PATH"
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
"$DIR/cs" open --id intellij-idea
