#!/bin/bash
# Generated by `cs build` - do not edit.
# @raycast.schemaVersion 1
# @raycast.title Open Cheatsheet
# @raycast.mode silent
# @raycast.packageName Cheatsheets
# @raycast.icon 📒
# @raycast.description Open the best-matching cheatsheet image
# @raycast.argument1 { "type": "text", "placeholder": "title or tag" }
export PATH="/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:$PATH"
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
"$DIR/cs" open "$1"
