#!/bin/bash
# Generated by `cs build` - do not edit.
# @raycast.schemaVersion 1
# @raycast.title Search Cheatsheets
# @raycast.mode fullOutput
# @raycast.packageName Cheatsheets
# @raycast.icon 🔎
# @raycast.description Search cheatsheets by title, tag, or shortcut (e.g. "rename", "cmd shift o")
# @raycast.argument1 { "type": "text", "placeholder": "title, tag or shortcut" }
export PATH="/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:$PATH"
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
"$DIR/cs" search --plain "$1"
